# Generated by Django 3.0.7 on 2020-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='thenumber',
        ),
        migrations.AddField(
            model_name='number',
            name='number',
            field=models.IntegerField(default=0, verbose_name='the number'),
        ),
        migrations.AlterField(
            model_name='mytest',
            name='myfield',
            field=models.DateTimeField(auto_now_add=True, verbose_name='my field'),
        ),
    ]
