# Generated by Django 3.0.7 on 2020-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200706_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json',
            name='county',
            field=models.TextField(default='', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='json',
            name='json',
            field=models.TextField(default='', verbose_name='JSON'),
        ),
    ]
