# Generated by Django 3.0.7 on 2020-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200725_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonCountyPDFLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.TextField(default='', verbose_name='County')),
                ('json', models.TextField(default='', verbose_name='JSON')),
            ],
        ),
    ]
